[package]
name = "l2"
version = "0.1.0"
src = "src"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# foo = { path = "vendor/foo" }
starknet = ">=2.2.0"

[[target.starknet-contract]]
sierra = true