[profile.default]
src = "src"
out = "out"
libs = ["lib"]

tests = ["test/"]
[rpc_endpoints]
goerli = "${GOERLI_RPC}"
mainnet = "${MAINNET_RPC}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
